sudo: required

scala:
   - 2.11.11

matrix:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      language: scala

script:
  - bash sbt test

before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
